In [2]:
import numpy as np
a = np.array([[3,7,5],[8,4,3],[2,4,9]])
print(a)

[[3 7 5]
 [8 4 3]
 [2 4 9]]


In [3]:
print (np.amin(a,1))#rowwise smallest value

[3 3 2]


In [4]:
print (np.amax(a,1))#rowwise biggest value

[7 8 9]


In [5]:
print (np.amin(a))

2


In [6]:
print (np.amax(a))

9


In [7]:
print(np.amax(a,axis=1))#axis =0 will search column wise and axis=1 rowwise

[7 8 9]


In [8]:
print(np.ptp(a))

7


In [9]:
print(np.ptp(a,axis=0))

[6 3 6]


In [ ]:
matrix multiplication

In [11]:
import numpy as np
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)
arr2 = np.array([[9,8,7],[6,5,4],[3,2,1]])
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [13]:
res = np.multiply(arr1,arr2)
res

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [14]:
res1 = np.matmul(arr1,arr2)
res1

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [ ]:
sorting

In [16]:
import numpy as np
arr1 = np.array([[3,8,1,2],[9,5,4,8]])
np.sort(arr1,axis=1,kind='mergesort')

array([[1, 2, 3, 8],
       [4, 5, 8, 9]])

In [17]:
import numpy as np
arr = np.array ([12,90,541,12,213])
print(np.where(arr>12))

(array([1, 2, 4], dtype=int64),)


In [18]:
import numpy as np
arr = np.array ([[20,24],[50,19]])
print(np.where(arr>20))

(array([0, 1], dtype=int64), array([1, 0], dtype=int64))
