In [1]:
rng = np.random.default_rng(500)
rng.random(10)

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [3]:
rng = np.random.default_rng(500)
rng.random(10)

array([0.56674314, 0.85397799, 0.6453572 , 0.41115681, 0.46803194,
       0.82136122, 0.31252317, 0.78622079, 0.43555016, 0.24763021])

In [4]:
rng.integers(0,10,100)

array([4, 4, 3, 8, 1, 5, 5, 5, 9, 2, 2, 8, 7, 2, 4, 8, 1, 1, 9, 4, 4, 3,
       5, 5, 6, 3, 8, 4, 6, 1, 2, 2, 9, 4, 1, 2, 2, 4, 3, 6, 2, 9, 5, 8,
       4, 6, 5, 6, 8, 9, 8, 8, 1, 0, 9, 4, 9, 8, 1, 8, 4, 2, 6, 0, 7, 3,
       3, 3, 8, 4, 1, 2, 2, 8, 9, 6, 0, 1, 6, 3, 5, 4, 0, 9, 8, 1, 3, 6,
       0, 5, 3, 2, 3, 5, 1, 9, 6, 4, 1, 0], dtype=int64)

In [5]:
rng = np.random.default_rng(12345)
mean,stddev = 5, 1
random_normal = rng.normal(mean, stddev, size=10)
random_normal

array([3.57617496, 6.26372846, 4.12933826, 4.74082677, 4.92465669,
       4.25911535, 3.6322073 , 5.6488928 , 5.36105811, 3.04713694])

In [6]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
arr[2]

2

In [8]:
random_normal[2]

4.129338262040914

In [9]:
arr[-2]

10

In [10]:
arr[:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [11]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
arr[::2] # arr[start:stop:step size]

array([ 0,  2,  4,  6,  8, 10])

In [13]:
newarr = arr.reshape(3,4)
newarr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
newarr[:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
newarr[1:, :]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
newarr[:,1:]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [17]:
newarr[2,1]

9

In [18]:
narr = np.array([2.7,-8.2,-0.0,12])
narr

array([ 2.7, -8.2, -0. , 12. ])

In [19]:
np.floor(narr)

array([ 2., -9., -0., 12.])

In [20]:
np.ceil(narr)

array([ 3., -8., -0., 12.])

In [21]:
tup1 = [(10,20,30),(40,50,60)]
array1 =np.asarray(tup1)
array1

array([[10, 20, 30],
       [40, 50, 60]])

In [22]:
array2 = np.array([[1,2,3],[4,5,6]])
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
np.add(array1,array2)

array([[11, 22, 33],
       [44, 55, 66]])

In [24]:
np.divide(array1,array2)

array([[10., 10., 10.],
       [10., 10., 10.]])

In [25]:
np.power(array1,array2)

array([[        10,        400,      27000],
       [   2560000,  312500000, -588640256]])

In [26]:
text_arr = np.array([['a','b','c']])
text_arr

array([['a', 'b', 'c']], dtype='<U1')

In [27]:
np.char.upper(text_arr)

array([['A', 'B', 'C']], dtype='<U1')

In [28]:
np.char.upper(text_arr)

array([['A', 'B', 'C']], dtype='<U1')

In [30]:
str = 'Tod;ay;is;a;rainy;day'
str

'Tod;ay;is;a;rainy;day'

In [31]:
np.char.split(str,sep=';')

array(list(['Tod', 'ay', 'is', 'a', 'rainy', 'day']), dtype=object)

In [32]:
np.char.join('-','dmy')

array('d-m-y', dtype='<U5')

In [33]:
np.char.replace('GOOD FOOD GOOD MOOD', 'O','X')

array('GXXD FXXD GXXD MXXD', dtype='<U19')

In [34]:
str1 = 'GOOD FOOD GOOD MOOD'
np.char.replace(str1[6],'O','R')

array('R', dtype='<U1')

In [35]:
str1

'GOOD FOOD GOOD MOOD'