In [1]:
import numpy as np

In [2]:
array = np.array(range(5))
array

array([0, 1, 2, 3, 4])

In [3]:
array_2d = np.array([range(5), range(5)])
array_2d + 5

array([[5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9]])

In [4]:
array.shape

(5,)

In [5]:
array_2d.shape

(2, 5)

In [6]:
array_2d.T.shape #T stands for transpose (interchanging rows and columns)

(5, 2)

In [7]:
array_2d.T

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [8]:
array.size #count of the data

5

In [9]:
array_2d.size

10

In [10]:
array.ndim

1

In [11]:
array_2d.ndim

2

In [12]:
array.dtype

dtype('int32')

In [13]:
array_2d.dtype

dtype('int32')