In [1]:
import numpy as np

In [2]:
array = np.array(range(5))
array

array([0, 1, 2, 3, 4])

In [3]:
array_2d = np.array([range(5), range(5)])
array_2d + 5

array([[5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9]])

In [4]:
array.shape

(5,)

In [5]:
array_2d.shape

(2, 5)

In [6]:
array_2d.T.shape #T stands for transpose (interchanging rows and columns)

(5, 2)

In [7]:
array_2d.T

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [8]:
array.size #count of the data

5

In [9]:
array_2d.size

10

In [10]:
array.ndim

1

In [11]:
array_2d.ndim

2

In [12]:
array.dtype

dtype('int32')

In [13]:
array_2d.dtype

dtype('int32')

In [15]:
array_text = np.array(['I','love','Python'])
array_text

array(['I', 'love', 'Python'], dtype='<U6')

In [16]:
array_text.dtype

dtype('<U6')

In [17]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
np.ones(5, dtype='int')

array([1, 1, 1, 1, 1])

In [19]:
np.zeros(50, 'int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

In [20]:
np.zeros(50, 'int').reshape(10,5)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [21]:
np.zeros((5,10), 'int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [22]:
np.identity(12)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [23]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(6,14).reshape(2,4)

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [25]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [26]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [27]:
np.linspace(8,64,8)

array([ 8., 16., 24., 32., 40., 48., 56., 64.])

In [28]:
np.linspace(8,80,10) #array([8.,16.,......80.])
 

array([ 8., 16., 24., 32., 40., 48., 56., 64., 72., 80.])